changelog:
  categories:
    - title: Features
      labels:
        - enhancement
        - feature
    - title: Fixes
      labels:
        - bug
        - fix
    - title: Documentation
      labels:
        - documentation
    - title: Maintenance
      labels:
        - chore
    - title: Other changes
      labels:
        - "*"
  exclude:
    labels:
      - skip-changelog
